services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "$$$$", "-C", "1"]
      interval: 5s
      timeout: 10s
      retries: 3

  gateway-simulator:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-simulator
    environment:
      - GATEWAY_PORT=6000
      - MQTT_BROKER_ADDRESS=mqtt-broker:1883  # Use the service name for DNS resolution
      - API_URL=http://host.docker.internal:8000
    ports:
      - "6000:6000"
    depends_on:
      mqtt-broker:
        condition: service_healthy
    networks:
      - iot-network
  
  rules-engine:
    build:
      context: ./rules_engine
      dockerfile: Dockerfile
    container_name: rules-engine
    depends_on:
      mqtt-broker:
        condition: service_started
      # Removed dependency on non-existent 'api' service
    networks:
      - iot-network
    volumes:
      - ./rules_engine/config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml", "--verbose"]
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge
    # No fixed subnet - let Docker handle the networking